### ISSUE TITLE
Connect button not working

### ISSUE THREAD

**Issue by CarterKJ** [MikeCoder96/HappyLighting-py#7]
The connect button does nothing when pressed, I tried restarting, uninstalling the official app, and updating bleak,
Is there anything that I'm missing?

**Comment by MikeCoder96** [comment]
Please enable debug logs and paste here a screenshot 
To enable debug go to Utils.py and set  
 ​DEBUG_LOGS​ ​=​ ​True

**Comment by CarterKJ** [comment]
When running pyhl.py with debug on, pressing scan outputs nothing to the console, only the "Start Capture" button works with debug and it outputs "[+] (39, 40, 34)"

**Comment by MikeCoder96** [comment]
First of all, thanks that you pointed out an oversight that is the "Start Capture" unlocked even if you aren't connected to a device.
With a debug logs, you have to press "Scan" button in order to search for a device. If it will be found, you will see something like this:
![image](https://user-images.githubusercontent.com/50410305/202999158-f864179b-e552-42dc-8d12-8c7816405ce6.png)
And from here, you have to connect to device pressing "Connect" button.
Keep in mind, this application is only for QHM Device that use HappyLighting mobile application.
If you have different device that use HappyLighting, let me know and we will work to make it compatible with Python App
